Lab6
rurkk/rurkk.github.io pull request #5
Opened 2024-12-03 18:09 UTC by rurkk

2024-12-11 11:09 UTC, Menemi requested changes

2024-12-11 11:09 UTC, Menemi commented on scripts/fetch.js
> +            errorMessage.innerHTML = `⚠ Что-то пошло не так: ${error.message}`;
аналогичная проблема, как и в прошлой лабе: `innerHTML` -> `appendChild`

в остальном ок

2024-12-22 17:45 UTC, rurkk commented on scripts/fetch.js
> +            errorMessage.innerHTML = `⚠ Что-то пошло не так: ${error.message}`;
готово

2024-12-23 13:10 UTC, Menemi approved these changes

2026-02-12 18:38 UTC, merged

2026-02-13 11:48 UTC, Menemi commented
своевременный мердж))

2026-02-14 14:29 UTC, rurkk commented
Ah shit, here we go again
________________________________
От: Титов Даниил ***@***.***>
Отправлено: 13 февраля 2026 г. 14:48
Кому: rurkk/rurkk.github.io ***@***.***>
Копия: Муллаянов Рауль Ильшатович ***@***.***>; State change ***@***.***>
Тема: Re: [rurkk/rurkk.github.io] Lab6 (PR #5)

[https://avatars.githubusercontent.com/u/47279903?s=20&v=4]Menemi left a comment (rurkk/rurkk.github.io#5)<https://github.com/rurkk/rurkk.github.io/pull/5#issuecomment-3896761726>

своевременный мердж))

—
Reply to this email directly, view it on GitHub<https://github.com/rurkk/rurkk.github.io/pull/5#issuecomment-3896761726>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A25M37PCRNRLUNECISD7U3L4LW2ZFAVCNFSM6AAAAABS6MCXKGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTQOJWG43DCNZSGY>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>